title: Nguyen Tan Ho's Homepage
page-top-title: Nguyen Tan Ho
top-section-bg-text: Computer Science
home-subtitle: Computer Vision&ensp;|&ensp; AI R&D Engineer
copyright-text: '&copy; Nguyen Tan Ho 2025-2026. All Rights Reserved.'
